<link rel="stylesheet" href="/css/attendance.css">
<link rel="stylesheet" href="/css/tooltip.css">
<link rel="stylesheet" href="/css/lib/datepicker/bootstrap-datepicker3.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/js/bootstrap-datetimepicker.min.js"></script>

<?php
$headers = [];
foreach ($this->dayList as $userId => $attendances) {
    foreach ($this->dayList[$userId] as $date => $items) {
        if (is_array($items)) {
            foreach ($items as $item) {
                $year = $item['year'] < date('Y') ? $item['year'] : '';
                $headers[$date] = $year . ' ' . $item['month'] . ' ' . $item['day'];
            }
        }
    }
}

function array_sort_by_column(&$array) {
    $reference_array = [];

    foreach($array as $key => $row) {
        $reference_array[] = $key;
    }

    array_multisort($reference_array, SORT_ASC, $array);
}
array_sort_by_column($headers);

?>
<div class="container-fluid">
    <!-- Start Page Content -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <h1 class="card-title"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;Asistencias</h1>
                            <h2 class="card-subtitle">Listado</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-6 form-group top_search">
                            <form method="POST" class="form-inline">
                                <div class="form-group mr-3">
                                    <label for="startDate">Start Date</label>
                                    <input id="startDate" name="start_date" type="text" class="form-control" value="<?= isset($_POST['start_date']) ? $_POST['start_date'] : '' ?>" />
                                </div>
                                <div class="form-group mr-3">
                                    <label for="endDate">End Date</label>
                                    <input id="endDate" name="end_date" type="text" class="form-control" value="<?= isset($_POST['end_date']) ? $_POST['end_date'] : '' ?>" />
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-outline-secondary mt-4 w-170" type="submit">
                                        <i class="fa fa-search">&nbsp;</i>
                                    </button>
                                </div>
                            </form>
                        </div>

                        <div class="col-md-6 col-sm-12 col-xs-6 form-group top_search form-inline">
                            <div class="form-group">
                                <label>Legend</label>
                                <div class="form-control h-100" style="padding: 0.5rem .75rem">
                                    <div class="mr-3" style="display: inline-block">
                                        <span class="badge legend-badge badge-success"> </span> <span class="vertical-alg">ENTRADA</span>
                                    </div>
                                    <div class="mr-3" style="display: inline-block">
                                        <span class="badge legend-badge badge-info"> </span> <span class="vertical-alg">SALIDA ALMUERZO</span>
                                    </div>
                                    <div class="mr-3" style="display: inline-block">
                                        <span class="badge legend-badge badge-warning"> </span> <span class="vertical-alg">REGRESO ALMUERZO</span>
                                    </div>
                                    <div class="mr-3" style="display: inline-block">
                                        <span class="badge legend-badge badge-secondary"> </span> <span class="vertical-alg">SALIDA</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content">
                            <div class="table-responsive">
                                <?php
                                    if (count($headers) <= 0) {
                                        echo '<b>No se encontraron resultados</b>';
                                    } else {
                                ?>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th width="30" class="main-td">#</th>
                                        <th width="200" class="main-td">
                                            <span class="item">First name</span>
                                        </th>
                                        <?php
                                            foreach($headers as $header) {
                                        ?>
                                            <th width="150" class="main-td">
                                                <span class="item"><?= $header ?></span>
                                            </th>
                                        <?php
                                            }
                                        ?>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    $n = 1;
                                    foreach ($this->dayList as $userId => $attendances) {
                                    ?>
                                        <tr>
                                            <td width="30" class="main-td">
                                                <span class="item"><?= $n ?></span>
                                            </td>
                                            <td width="200">
                                                <span class="item"><?= $this->dayList[$userId]['full_name'] ?></span>
                                            </td>

                                            <?php foreach ($headers as $date => $dateDesc) {
                                                    echo '<td width="150">';
                                                    if (isset($this->dayList[$userId][$date])) {
                                                        foreach ($this->dayList[$userId][$date] as $item) {
                                            ?>
                                                            <?php $badgeType = ['#28a745', '#6c757d', '#17a2b8', '#ffc107']; ?>
                                                            <span class="badge badge-light badge-custom"
                                                                  tooltip="<?= $item['observacion'] ?>"
                                                                  style="border-left-color: <?= $badgeType[$item['status'] - 1] ?>;">
                                                                <?= $item['hour'] ?>
                                                            </span>
                                            <?php
                                                        }
                                                    }
                                                    echo '</td>';
                                                }

                                            ?>
                                        </tr>
                                    <?php
                                        $n += 1;
                                    }
                                    ?>
                                    </tbody>
                                </table>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End PAge Content -->
</div>
<script>
    $(function () {
        var sd = new Date(), ed = new Date();

        $('#startDate').datetimepicker({
            pickTime: false,
            format: "DD-MM-YYYY",
            defaultDate: sd,
            maxDate: ed
        });

        $('#endDate').datetimepicker({
            pickTime: false,
            format: "DD-MM-YYYY",
            defaultDate: ed,
            minDate: sd
        });
    });
</script>
