<?php

$title = $this->titulo;
$this->headTitle($title);

$form = $this->form;
//$form->setAttribute('action', $this->url());
$form->setAttribute('class', 'form-horizontal form-label-left');

$isEdit = (!empty($this->isEdit) ? true : false);
$btnDsc = 'Grabar';
$campos = $this->campos;
$descripciones = $this->camposDescripcion;

foreach ($campos as $keyField => $field) {
    $tipoDato = '';
    if (!empty($field['TIPO'])&& $field['TIPO'] == 'DATE'){
        $tipoDato = 'date-picker';
    }
    if(!empty($field['TIPO'])&& $field['TIPO'] == 'DOUBLE'){
        $tipoDato = 'double';
    }
    if(!empty($field['TIPO'])&& $field['TIPO'] == 'TIME'){
        $tipoDato = 'time';
    }
    $showField = false;

    if ((((empty($field['AI']) || $field['AI'] == 0) && !$isEdit) || $isEdit) && empty($field['FK'])) {
        $form->add([
            'name' => $keyField,
            'type' => 'text',
            'attributes' => [
                'id' => $keyField,
                'autocomplete' =>  (!empty($field['DATE']) || (!empty($field['TIPO']) && $field['TIPO'] == 'DATE' ) ? 'off' : ''),
                'class' => 'form-control col-md-12 col-xs-12 ' . $tipoDato,
                'maxlength' => (isset($field['LENGHT']) ? $field['LENGHT'] : null),
                'required' => isset($field['REQUIRED']) ? $field['REQUIRED'] : '',
                'value' => (!empty($this->defaultValue[$keyField]) ? $this->defaultValue[$keyField] : ''),
                'placeholder' => 'Inserte aquí',
                'readonly' => ((!empty($field['PK'] && !empty($field['AI'])) || !empty($field['DATE']) ||  !empty($field['PK'])) ? 'readonly' : ''),
                'icon' => (!empty($field['ICON']) ? $field['ICON'] : ''),
            ],
            'options' => [
                'label' => $descripciones[$keyField],
                'label_attributes' => array(
                    'class' => 'control-label col-md-3 col-sm-3 col-xs-3 offset-md-1 offset-sm-1 offset-xs-1',
                ),
            ],
        ]);

        $showField = true;
    }

    if (!empty($field['FK'])) {
        $form->add([
            'name' => $keyField,
            'type' => 'select',
            'attributes' => [
                'id' => $keyField,
                'class' => 'form-control col-md-12 col-xs-12',
                'required' => isset($field['REQUIRED']) ? $field['REQUIRED'] : '',
                'value' => (!empty($this->defaultValue[$keyField]) ? $this->defaultValue[$keyField] : ''),
                'multiple' => !empty($field['multiple']) ? $field['multiple'] : []
            ],
            'options' => [
                'label' => $descripciones[$keyField],
                'label_attributes' => [
                    'class' => 'text-danger control-label col-md-3 col-sm-3 col-xs-3 offset-md-1 offset-sm-1 offset-xs-1',
                ],
                'value_options' => !empty($field['FUNC']) ? $this->fk[$field['FUNC']] : [],
            ],
        ]);

        $showField = true;
    }

    if ($showField) {
        $formFields[] = $form->get($keyField);
    }
}

$form->add([
    'type' => 'button',
    'name' => 'reset',
    'attributes' => [
        'class' => 'btn btn-danger col-12',
        'onclick' => 'history.back()',
        'type' => 'reset',
    ],
    'options' => [
        'label' => '<i class="fa fa-trash-o"></i> Cancelar',
        'label_options' => [
            'disable_html_escape' => true,
        ]
    ],
]);

$form->add([
    'type' => 'submit',
    'attributes' => [
        'class' => 'btn btn-success col-12'
    ],
    'options' => [
        'label' => '<i class="fa fa-save"></i> Grabar',
        'label_options' => [
            'disable_html_escape' => true,
        ]
    ],
]);
$submit = $form->get('submit');
$reset = $form->get('reset');

$form->prepare();
?>
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="form-validation">
                <div class="x_content">
                    <div class="row">
                        <div class="offset-1">
                            <div class="title_left">
                                <h1 class="card-title">
                                    <i class="fa fa-cubes" aria-hidden="true"></i>
                                   <?= $this->escapeHtml($title); ?>
                                </h1>
                                <h2 class="card-subtitle">
                                    Agregar
                                </h2>
                            </div>
                        </div>
                    </div>
                    <br>
                    <?php foreach ($formFields as $key => $field): ?>
                        <div class="form-group row fr<?= $key ?>">
                            <?= $this->formLabel($field) ?>
                            <div class="col-md-7 col-sm-7 col-xs-7 input-group">
                                <?php if (!empty($field->getAttributes()['icon'])) { ?>
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fa fa-<?= $field->getAttributes()['icon']; ?>" aria-hidden="true"></i>
                                        </div>
                                    </div>
                                <?php } ?>
                                <?= $this->formElement($field) ?>
                                <?= $this->formElementErrors()->render($field, ['class' => 'help-block']) ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-sm-3 col-xs-3">
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <?= $this->formButton($submit); ?>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <?= $this->formButton($reset); ?>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                    </div>
                </div>
            </div>
            <?php
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
