<?= $this->doctype() ?>
<html lang="en">
<head>

    <meta charset="utf-8">
   <?=
   $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
   ?>
    <!-- Favicon icon -->
   <?= $this->headTitle(\Business\Settings::BusinessName)->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Le styles -->
   <?=
   $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/images/favicon.ico'])
      ->prependStylesheet($this->basePath('css/lib/bootstrap/bootstrap.min.css'))
      ->prependStylesheet($this->basePath('css/lib/calendar2/semantic.ui.min.css'))
      ->prependStylesheet($this->basePath('css/lib/calendar2/pignose.calendar.min.css'))
      ->prependStylesheet($this->basePath('css/helper.css'))
      ->prependStylesheet($this->basePath('css/lib/sweetalert/sweetalert.css'))
      ->prependStylesheet($this->basePath('bower_components/multiselect/css/multi-select.css'))
      ->prependStylesheet($this->basePath('css/style.css'))
	  ->prependStylesheet($this->basePath('css/chosen.min.css'))
      ->prependStylesheet($this->basePath('css/lib/multiple-emails/multiple-emails.css'))
   ?>
   <?=
   $this->headScript()
      ->appendFile($this->basePath('js/lib/jquery/jquery.min.js'))
      ->appendFile($this->basePath('js/lib/bootstrap/js/popper.min.js'))
      ->appendFile($this->basePath('js/lib/bootstrap/js/bootstrap.min.js'))
      ->appendFile($this->basePath('js/jquery.slimscroll.js'))
      ->appendFile($this->basePath('js/sidebarmenu.js'))
      ->appendFile($this->basePath('js/lib/sticky-kit-master/dist/sticky-kit.min.js'))
      ->appendFile($this->basePath('js/lib/morris-chart/raphael-min.js'))
      ->appendFile($this->basePath('js/lib/morris-chart/morris.js'))
      ->appendFile($this->basePath('js/lib/morris-chart/dashboard1-init.js'))
      ->appendFile($this->basePath('js/lib/calendar-2/moment.latest.min.js'))
      ->appendFile($this->basePath('js/lib/calendar-2/semantic.ui.min.js'))
      ->appendFile($this->basePath('js/lib/calendar-2/prism.min.js'))
      ->appendFile($this->basePath('js/lib/sweetalert/sweetalert.min.js'))
      ->appendFile($this->basePath('bower_components/multiselect/js/jquery.multi-select.js'))
      ->appendFile($this->basePath('js/scripts.js'))
      ->appendFile($this->basePath('js/script.js'))
	  ->appendFile($this->basePath('js/chosen.proto.min.js'))
	  ->appendFile($this->basePath('js/chosen.jquery.min.js'))
      ->appendFile($this->basePath('js/lib/multiple-emails/multiple-emails.js'))
      ->appendFile($this->basePath('js/lib/ckeditor/ckeditor.js'))
   ?>
</head>

<body class="fix-header fix-sidebar">
<!-- Preloader - style you can find in spinners.css -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
</div>
<!-- Main wrapper  -->
<div id="main-wrapper">
    <!-- header header  -->
    <div class="header">
        <nav class="navbar top-navbar navbar-expand-md navbar-light">
            <!-- Logo -->
            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->url('dashboard-index') ?>">
                    <!-- Logo icon -->
                    <b>
                        <img width="30" src="/images/fgt_logo_mb.png">
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span><img width="100" src="/images/fgt_logo_mb_txt.png"></span>
                </a>
            </div>
            <!-- End Logo -->
            <div class="navbar-collapse">
                <!-- toggle and nav items -->
                <ul class="navbar-nav mr-auto mt-md-0">
                    <!-- This is  -->
                    <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted  " href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                    <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                    <!-- Messages -->
                    <!--
                    <li class="nav-item dropdown mega-dropdown"> <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-th-large"></i></a>
                        <div class="dropdown-menu animated zoomIn">

                           <ul class="mega-dropdown-menu row">
                               <li class="col-lg-3  m-b-30">
                                   <h4 class="m-b-20">CONTACT US</h4>
                                   <form>
                                       <div class="form-group">
                                           <input type="text" class="form-control" id="exampleInputname1" placeholder="Enter Name"> </div>
                                       <div class="form-group">
                                           <input type="email" class="form-control" placeholder="Enter email"> </div>
                                       <div class="form-group">
                                           <textarea class="form-control" id="exampleTextarea" rows="3" placeholder="Message"></textarea>
                                       </div>
                                       <button type="submit" class="btn btn-info">Submit</button>
                                   </form>
                               </li>
                               <li class="col-lg-3 col-xlg-3 m-b-30">
                                   <h4 class="m-b-20">List style</h4>
                                   <ul class="list-style-none">
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                   </ul>
                               </li>
                               <li class="col-lg-3 col-xlg-3 m-b-30">
                                   <h4 class="m-b-20">List style</h4>
                                   <ul class="list-style-none">
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                   </ul>
                               </li>
                               <li class="col-lg-3 col-xlg-3 m-b-30">
                                   <h4 class="m-b-20">List style</h4>
                                   <ul class="list-style-none">
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                       <li><a href="javascript:void(0)"><i class="fa fa-check text-success"></i> This Is Another Link</a></li>
                                   </ul>
                               </li>
                           </ul>
                       </div>
                   </li>
                            -->
               </ul>
                <!-- User profile and search -->
                <ul class="navbar-nav my-lg-0">

                    <!-- Search -->
                    <!--
                    <li class="nav-item hidden-sm-down search-box"> <a class="nav-link hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-search"></i></a>
                        <form class="app-search">
                            <input type="text" class="form-control" placeholder="Search here"> <a class="srh-btn"><i class="ti-close"></i></a> </form>
                    </li>
                    -->
                    <!-- Comment -->
                    <!--
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-muted text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-bell"></i>
                            <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right mailbox animated zoomIn">
                            <ul>
                                <li>
                                    <div class="drop-title">Notifications</div>
                                </li>
                                <li>
                                    <div class="message-center">
                                        <a href="#">
                                            <div class="btn btn-danger btn-circle m-r-10"><i class="fa fa-link"></i></div>
                                            <div class="mail-contnet">
                                                <h5>This is title</h5> <span class="mail-desc">Just see the my new admin!</span> <span class="time">9:30 AM</span>
                                            </div>
                                        </a>
                                        <a href="#">
                                            <div class="btn btn-success btn-circle m-r-10"><i class="ti-calendar"></i></div>
                                            <div class="mail-contnet">
                                                <h5>This is another title</h5> <span class="mail-desc">Just a reminder that you have event</span> <span class="time">9:10 AM</span>
                                            </div>
                                        </a>
                                        <a href="#">
                                            <div class="btn btn-info btn-circle m-r-10"><i class="ti-settings"></i></div>
                                            <div class="mail-contnet">
                                                <h5>This is title</h5> <span class="mail-desc">You can customize this template as you want</span> <span class="time">9:08 AM</span>
                                            </div>
                                        </a>
                                        <a href="#">
                                            <div class="btn btn-primary btn-circle m-r-10"><i class="ti-user"></i></div>
                                            <div class="mail-contnet">
                                                <h5>This is another title</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span>
                                            </div>
                                        </a>
                                    </div>
                                </li>
                                <li>
                                    <a class="nav-link text-center" href="javascript:void(0);"> <strong>Check all notifications</strong> <i class="fa fa-angle-right"></i> </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    -->
                    <!-- End Comment -->
                    <!-- Messages -->
                    <!--
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-muted  " href="#" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-envelope"></i>
                            <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right mailbox animated zoomIn" aria-labelledby="2">
                            <ul>
                                <li>
                                    <div class="drop-title">You have 4 new messages</div>
                                </li>
                                <li>
                                    <div class="message-center">
                                        <a href="#">
                                            <div class="user-img"> <img src="images/users/5.jpg" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>
                                            <div class="mail-contnet">
                                                <h5>Michael Qin</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span>
                                            </div>
                                        </a>
                                        <a href="#">
                                            <div class="user-img"> <img src="images/users/2.jpg" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
                                            <div class="mail-contnet">
                                                <h5>John Doe</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span>
                                            </div>
                                        </a>
                                        <a href="#">
                                            <div class="user-img"> <img src="images/users/3.jpg" alt="user" class="img-circle"> <span class="profile-status away pull-right"></span> </div>
                                            <div class="mail-contnet">
                                                <h5>Mr. John</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span>
                                            </div>
                                        </a>
                                        <a href="#">
                                            <div class="user-img"> <img src="images/users/4.jpg" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span> </div>
                                            <div class="mail-contnet">
                                                <h5>Michael Qin</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span>
                                            </div>
                                        </a>
                                    </div>
                                </li>
                                <li>
                                    <a class="nav-link text-center" href="javascript:void(0);"> <strong>See all e-Mails</strong> <i class="fa fa-angle-right"></i> </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    -->
                    <!-- End Messages -->
                    <!-- Profile -->
                    <?php if (!empty($this->identity()->empresa['empnom'])) { ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-muted text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               <span style="font-size: 1em;"><b><?php echo $this->identity()->empresa['empnom']; ?></b></span>
                        </a>
                        <!--
                        <div class="dropdown-menu dropdown-menu-right mailbox animated zoomIn">
                            <ul>
                                <li>
                                    <div class="drop-title">Notifications</div>
                                </li>
                                <li>
                                    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 250px;"><div class="message-center" style="overflow: hidden; width: auto; height: 250px;">

                                            <a href="#">
                                                <div class="btn btn-danger btn-circle m-r-10"><i class="fa fa-link"></i></div>
                                                <div class="mail-contnet">
                                                    <h5>This is title</h5> <span class="mail-desc">Just see the my new admin!</span> <span class="time">9:30 AM</span>
                                                </div>
                                            </a>

                                            <a href="#">
                                                <div class="btn btn-success btn-circle m-r-10"><i class="ti-calendar"></i></div>
                                                <div class="mail-contnet">
                                                    <h5>This is another title</h5> <span class="mail-desc">Just a reminder that you have event</span> <span class="time">9:10 AM</span>
                                                </div>
                                            </a>

                                            <a href="#">
                                                <div class="btn btn-info btn-circle m-r-10"><i class="ti-settings"></i></div>
                                                <div class="mail-contnet">
                                                    <h5>This is title</h5> <span class="mail-desc">You can customize this template as you want</span> <span class="time">9:08 AM</span>
                                                </div>
                                            </a>

                                            <a href="#">
                                                <div class="btn btn-primary btn-circle m-r-10"><i class="ti-user"></i></div>
                                                <div class="mail-contnet">
                                                    <h5>This is another title</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span>
                                                </div>
                                            </a>
                                        </div><div class="slimScrollBar" style="background: rgb(220, 220, 220); width: 5px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px;"></div><div class="slimScrollRail" style="width: 5px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div></div>
                                </li>
                                <li>
                                    <a class="nav-link text-center" href="javascript:void(0);"> <strong>Check all notifications</strong> <i class="fa fa-angle-right"></i> </a>
                                </li>
                            </ul>
                        </div>
                        -->
                    </li>
                    <?php } ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div alt="user" class="profile-pic">
                               <?php echo $this->identity()->full_name[0]; ?>
                            </div>
                            <i class="fa fa-caret-down" aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right animated zoomIn">
                            <ul class="dropdown-user">
                                <!--
                                <li><a href="#"><i class="ti-user"></i> Profile</a></li>
                                <li><a href="#"><i class="ti-wallet"></i> Balance</a></li>
                                <li><a href="#"><i class="ti-email"></i> Inbox</a></li>
                                <li><a href="#"><i class="ti-settings"></i> Setting</a></li>
                                -->
                                <li><a href="<?= $this->url('dashboard-logout') ?>"><i class="fa fa-power-off"></i> Logout</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <!-- End header header -->
    <!-- Left Sidebar  -->
   <?php
   $navigation = $this->navigation('Dashboard\Menu');
   echo $navigation
      ->menu()
      ->setPartial('layout/menu')
      ->render();
   ?>
    <!-- End Left Sidebar  -->
    <!-- Page wrapper  -->
    <div class="page-wrapper">
        <!-- Bread crumb -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3>Dashboard
                </h3> </div>
            <div class="col-md-7 align-self-center">
            </div>
        </div>
        <!-- End Bread crumb -->
        <!-- Container fluid  -->
        <div class="container-fluid">
            <!-- Start Page Content -->
           <?= $this->content ?>
            <!-- End PAge Content -->
        </div>
        <!-- End Container fluid  -->
        <!-- footer -->
        <!--
        <footer class="footer"> © <?= date('Y') ?> Todos los Derechos Reservados
        <i class="fa fa-globe"></i> <?= \Business\Settings::BusinessName ?></footer>
        -->
        <!-- End footer -->
    </div>
    <!-- End Page wrapper  -->
</div>
<!-- End Wrapper -->

<!-- Scripts -->
<?php $this->FlashMsg(); ?>
<?= $this->inlineScript() ?>
<script>
    // $('.date-picker').datepicker({
    //     language: 'es',
    //     format: 'dd/mm/yyyy',
    //     autoclose: true
    // });
    // $('.date-picker').mask('00/00/0000');
    // $('.time').mask('00:00');
    $(".chosen-select").chosen({disable_search_threshold: 10});
</script>
</body>
</html>
